### ISSUE TITLE
latest version of the appium-desktop

### ISSUE THREAD

**Issue by npagare** [usamaejaz/chocolatey-packages#1]
Hi,

When will the latest version of the appium-desktop be available under chocolatey repository?

The current version on the Appium's site is 1.6.1 - https://github.com/appium/appium-desktop/releases/tag/v1.6.1

Thanks

**Comment by npagare** [comment]
When tried to upgrade to v1.6.1
![image](https://user-images.githubusercontent.com/26844611/40866489-785de64e-65c3-11e8-88f6-29b51fc6f084.png)

I get following error 

![image](https://user-images.githubusercontent.com/26844611/40866459-61f48d54-65c3-11e8-8376-8613878a0d25.png)

**Comment by usamaejaz** [comment]
I have submitted version 1.6.1 to chocolatey feed. It's pending review and will be available shortly. You can check it out at https://chocolatey.org/packages/appium-desktop/1.6.1 in the meantime. 

Regarding that JavaScript error, appium-desktop developers will be able to shed some light on it. (i see you have already opened an issue there, let's see)

**Comment by npagare** [comment]
Hi @usamaejaz , thank you for your quick response and help in addressing this.

Going forward - will this update be automated ?

Thanks,

**Comment by usamaejaz** [comment]
I have not set up automatic updates for chocolatey at the moment but I plan to do so.

**Comment by npagare** [comment]
Hi @usamaejaz ,

There is a new update to Appium-desktop package. Will you please make it available on choco?


Thanks,

**Comment by usamaejaz** [comment]
@IoTFier, It has been pushed to choco repository https://chocolatey.org/packages/appium-desktop/1.6.2

**Comment by npagare** [comment]
Hi @usamaejaz , thank you. But, it is still not showing up in the choco upgrade command.

Thanks,

**Comment by usamaejaz** [comment]
@IoTFier, it will be available as soon as it's approved by chocolatey moderators. Try passing the version to `choco` for now but I am not sure if that will work even when the version is pending a review.

**Comment by npagare** [comment]
Thank you. Please try to set up this as an automation upgrade.

**Comment by usamaejaz** [comment]
It's on my todo list now. Thank you for reminding me.

**Comment by npagare** [comment]
Hi @usamaejaz, the upgrade package is still not available on choco.
It has been over 9 days. Can you please check with the reviewer?
Thanks

**Comment by usamaejaz** [comment]
It might take a while. But for the time being, refer to https://chocolatey.org/faq#how-do-i-install-a-package-version-under-moderation to install a package which is pending moderation.

**Comment by npagare** [comment]
How long @usamaejaz,
With this experience, I don't think this application should be supported under chocoloatey.
It just defeats the purpose.

**Comment by usamaejaz** [comment]
I did contact them. The queue has many packages waiting to be approved. We cannot speed up the review process. 
You can install it in the meantime:
`choco install appium-desktop --version 1.6.2`
